package models

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math/rand"
	"net/http"
	"time"
	"treehole_next/config"
	"treehole_next/utils"
)

const (
	timeout = time.Second * 10
)

var client = http.Client{Timeout: timeout}

/*
	{
		"data": { // database model, struct, only need once Marshal at the end
		"additionalProp1": "string",
		"additionalProp2": "string",
		"additionalProp3": "string"
		},
		"description": "string", // DON'T ADD, will be generated by microservice
		"recipients": [ // UserIds, []int, only need once Marshal at the end
		0
		],
		"title": "string", // DON'T ADD, will be generated by microservice
		"type": "favorite", // define by MessageType, string
		"url": "string" // relative api route, string
	}
*/
type Message map[string]any

type Messages []Message

type MessageType string

const (
	MessageTypeFavorite    MessageType = "favorite"
	MessageTypeReply       MessageType = "reply"
	MessageTypeMention     MessageType = "mention"
	MessageTypeModify      MessageType = "modify" // including fold and delete
	MessageTypePermission  MessageType = "permission"
	MessageTypeReport      MessageType = "report"
	MessageTypeReportDealt MessageType = "report_dealt"
)

func readRespMessage(body io.ReadCloser) Message {
	defer func(body io.ReadCloser) {
		err := body.Close()
		if err != nil {
			utils.Logger.Error("[notification] Close error: " + err.Error())
		}
	}(body)

	data, err := ioutil.ReadAll(body)
	if err != nil {
		utils.Logger.Error("[notification] Read body failed: " + err.Error())
		return Message{}
	}
	var response Message
	err = json.Unmarshal(data, &response)
	if err != nil {
		utils.Logger.Error("[notification] Unmarshal body failed: " + err.Error())
		return Message{}
	}
	return response
}

func (messages Messages) Merge(newMessage Message) Messages {
	if newMessage == nil {
		return messages
	}
	if len(messages) == 0 {
		return Messages{newMessage}
	}

	new, _ := newMessage["recipients"].([]int)
	for _, message := range messages {
		old, _ := message["recipients"].([]int)
		for _, r1 := range old {
			for id, r2 := range new {
				if r1 == r2 {
					new = append(new[:id], new[id+1:]...)
					break
				}
			}
		}
		if len(new) == 0 {
			return messages
		}
	}

	newMessage["recipients"] = new
	messages = append(messages, newMessage)
	return messages
}

func (messages Messages) Send() error {
	if messages == nil {
		return nil
	}

	for _, message := range messages {
		err := message.Send()
		if err != nil {
			return err
		}
	}
	return nil
}

func (message Message) Send() error {
	// only for test
	// message["recipients"] = []int{1}

	// construct form
	form, err := json.Marshal(message)
	if err != nil {
		utils.Logger.Error("[notification] error encoding notification" + err.Error())
		return err
	}

	// construct http request
	req, _ := http.NewRequest(
		"POST",
		fmt.Sprintf("%s/messages", config.Config.NotificationUrl),
		bytes.NewBuffer(form),
	)
	req.Header.Add("Content-Type", "application/json")

	// bench and simulation
	if config.Config.Mode == "bench" {
		time.Sleep(time.Millisecond)
		return nil
	}

	// get response
	resp, err := client.Do(req)
	if err != nil {
		utils.Logger.Error("[notification] error sending notification" + err.Error())
		return err
	}

	response := readRespMessage(resp.Body)
	if resp.StatusCode != 201 {
		utils.Logger.Error("[notification] notification response failed" + fmt.Sprint(response))
		return errors.New(fmt.Sprint(response))
	}

	return nil
}

type Admin struct {
	Id           int      `json:"id"`
	IsAdmin      bool     `json:"is_admin"`
	JoinedTime   string   `json:"joined_time"`
	LastLogin    string   `json:"last_login"`
	Nickname     string   `json:"nickname"`
	OffenseCount int      `json:"offense_count"`
	Roles        []string `json:"roles"`
}

func readRespAdmin(body io.ReadCloser) []Admin {
	defer func(body io.ReadCloser) {
		err := body.Close()
		if err != nil {
			utils.Logger.Error("[getadmin] Close error: " + err.Error())
		}
	}(body)

	data, err := ioutil.ReadAll(body)
	if err != nil {
		utils.Logger.Error("[getadmin] Read body failed: " + err.Error())
		return []Admin{}
	}
	var response []Admin
	err = json.Unmarshal(data, &response)
	if err != nil {
		utils.Logger.Error("[getadmin] Unmarshal body failed: " + err.Error())
		return []Admin{}
	}
	return response
}

var adminList []int

func InitAdminList() {
	// skip when bench
	if config.Config.Mode == "bench" {
		return
	}

	// construct http request
	req, _ := http.NewRequest(
		"GET",
		fmt.Sprintf("%s/users", config.Config.AuthUrl),
		nil,
	)
	query := req.URL.Query()
	query.Add("size", "0")
	query.Add("offset", "0")
	query.Add("role", "admin")
	req.URL.RawQuery = query.Encode()

	// get response
	resp, err := client.Do(req)

	// handle err
	if err != nil {
		utils.Logger.Error("[get admin] error sending auth server" + err.Error())
		return
	}

	response := readRespAdmin(resp.Body)

	if resp.StatusCode != 200 || len(response) == 0 {
		utils.Logger.Error("[get admin] auth server response failed" + fmt.Sprint(resp))
		return
	}

	// get ids
	for _, mention := range response {
		adminList = append(adminList, mention.Id)
	}

	// shuffle ids
	for i := range adminList {
		j := rand.Intn(i + 1)
		adminList[i], adminList[j] = adminList[j], adminList[i]
	}

	// panic(fmt.Sprint(adminList)) // Only for Test
}
